### ISSUE TITLE
发现fcc某个挑战的代码实例描述错误，但不知为何无法提交错误……

### ISSUE THREAD

**Issue by NBR-hugh** [NBR-hugh/freecodecamp-practice#7]

**Comment by NBR-hugh** [comment]
#### Challenge Name


https://www.freecodecamp.com/challenges/disable-an-element-using-jquery

#### Issue Description

an example in the decribtion like this:
$("button").prop("disabled", true);
but,the right one may be like this:
$("button").prop("disabled", "true");


#### Screenshot


![20161019174808](https://cloud.githubusercontent.com/assets/22027884/19513911/410a40ae-9624-11e6-92d3-ad1dbdc225e0.png)

**Comment by NBR-hugh** [comment]
蠢……

**Comment by soyaine** [comment]
可以到他们的 github 上提
